services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: hiddengem_db
    command: start --log trace --user ${SURREALDB_USER} --pass ${SURREALDB_PASS} rocksdb:///data/database.db
    ports:
      - "${DB_PORT}:8000"
    volumes:
      - C:/GatheredMagicDB:/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: HiddenGemMVC/dockerfile
    container_name: hiddengem_web
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      - surrealdb
    volumes: 
      - ./HiddenGemResources:/app/shared-data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ResourcePaths__KeywordsJson=/app/shared-data/Keywords.json
      - SurrealDb__Endpoint=http://surrealdb:8080
      - SurrealDb__User=${SURREALDB_USER}
      - SurrealDb__Pass=${SURREALDB_PASS}
      - SurrealDb__Namespace={SURREALDB_NS}
      - SurrealDb__Database={SURREALDB_DB}
    restart: unless-stopped

volumes:
  surreal_data:



