# -----------------------------------------
    # 1. Base Runtime Stage
    # -----------------------------------------
    # This creates the lightweight environment where your app will actually run.
    FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
    USER $APP_UID
    WORKDIR /app
    EXPOSE 8080
    
    # -----------------------------------------
    # 2. Build Stage
    # -----------------------------------------
    # Uses the heavier SDK image to compile your C# code.
    FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
    ARG BUILD_CONFIGURATION=Release
    WORKDIR /src
    
    # Copy all project files first (This caches the restore step to speed up future builds!)
    COPY ["HiddenGemMVC/HiddenGemMVC.csproj", "HiddenGemMVC/"]
    COPY ["HiddenGemDAL/HiddenGemDAL.csproj", "HiddenGemDAL/"]
    COPY ["HiddenGemBLL/HiddenGemBLL.csproj", "HiddenGemBLL/"]
    COPY ["HiddenGemShared/HiddenGemShared.csproj", "HiddenGemShared/"]
    
    # Restore NuGet packages for the MVC project (which will implicitly restore its dependencies)
    RUN dotnet restore "/src/HiddenGemMVC/HiddenGemMVC.csproj"
    
    # Copy the rest of your actual source code
    COPY . .
    
    # Move into the MVC directory and build the app
    WORKDIR "/src/HiddenGemMVC"
    RUN dotnet build "HiddenGemMVC.csproj" -c $BUILD_CONFIGURATION -o /app/build
    
    # -----------------------------------------
    # 3. Publish Stage
    # -----------------------------------------
    # Optimizes the build for deployment
    FROM build AS publish
    ARG BUILD_CONFIGURATION=Release
    RUN dotnet publish "HiddenGemMVC.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
    
    # -----------------------------------------
    # 4. Final Run Stage
    # -----------------------------------------
    # Copies the optimized files back into the lightweight runtime image
    FROM base AS final
    WORKDIR /app
    COPY --from=publish /app/publish .
    
    # Tell Docker how to start your web app
    ENTRYPOINT ["dotnet", "HiddenGemMVC.dll"]